Feature/docker
MAXXXIMUS-tropical-milkshake/MAXXXIMUS_Calculator pull request #6
Opened 2024-09-20 11:04 UTC by DaniilZ77

- dockerfile for backend
- docker compose (db + backend)

2024-09-20 11:30 UTC, petrukhinandrew requested changes

2024-09-20 11:30 UTC, petrukhinandrew commented on backend/Dockerfile
> +FROM golang:${GO_VERSION}-${GO_BASE_IMAGE}
add here `FROM .... as builder` (need for multistage)

2024-09-20 11:30 UTC, petrukhinandrew commented on backend/Dockerfile
> +RUN go build -o ./backend ./cmd/main.go
insert here something like 
```
FROM alpine
WORKDIR /app
COPY --from=builder /app/backend ./bin
CMD ["./app/bin/main"]
```

https://www.golinuxcloud.com/golang-docker-multi-stage-build/

2024-09-20 17:20 UTC, petrukhinandrew approved these changes, later dismissed

2024-09-20 19:19 UTC, k0oshara submitted a review, later dismissed

2024-09-20 19:20 UTC, k0oshara submitted a review, later dismissed

2024-09-21 11:21 UTC, petrukhinandrew approved these changes

2024-09-21 11:21 UTC, merged